drop table IF EXISTS friends, film_genre, likes, users, films, mpa, genres CASCADE;

create TABLE users
(
    user_id  INT4         generated by default as identity primary key,
    email    VARCHAR(100) NOT NULL
        CONSTRAINT "email_unique" UNIQUE,
    login    VARCHAR(100) NOT NULL
        CONSTRAINT "login_unique" UNIQUE,
    name     VARCHAR(100) NOT NULL,
    birthday DATE         NOT NULL
);

create TABLE friends
(
    user_id   INT4        NOT NULL,
    friend_id INT4        NOT NULL,
    CONSTRAINT user_friend_pkey
        PRIMARY KEY (user_id, friend_id),
    CONSTRAINT user_friends_fkey
        FOREIGN KEY (user_id)
            REFERENCES users (user_id)
            ON delete CASCADE,
    CONSTRAINT friend_friends_fkey
        FOREIGN KEY (friend_id)
            REFERENCES users (user_id)
            ON delete CASCADE,
    CONSTRAINT user_not_equals_friend CHECK ( user_id <> friend_id )
);

create TABLE mpa
(
    mpa_id          INT4         generated by default as identity primary key,
    mpa_name        VARCHAR(20)  NOT NULL,
    mpa_description VARCHAR(200) NOT NULL
);

create TABLE films
(
    film_id     INT4         generated by default as identity primary key,
    name        VARCHAR(200) NOT NULL,
    description VARCHAR(200) NOT NULL,
    release     DATE         NOT NULL,
    duration    INT2         NOT NULL,
    mpa_id      INT4         NOT NULL,
    CONSTRAINT film_mpa_fkey
        FOREIGN KEY (mpa_id)
            REFERENCES mpa (mpa_id)
            ON DELETE CASCADE
);

create TABLE genres
(
    genre_id    INT4         generated by default as identity primary key,
    genre_name  VARCHAR(50) NOT NULL
);

create TABLE film_genre
(
    film_id  INT4 NOT NULL,
    genre_id INT4 NOT NULL,
    CONSTRAINT film_genre_pkey
        PRIMARY KEY (film_id, genre_id),
    CONSTRAINT film_genre_fkey
        FOREIGN KEY (film_id)
            REFERENCES films (film_id)
            ON delete CASCADE,
    CONSTRAINT genre_film_fkey
        FOREIGN KEY (genre_id)
            REFERENCES genres (genre_id)
            ON delete CASCADE
);

create TABLE likes
(
    film_id INT4 NOT NULL,
    user_id INT4 NOT NULL,
    CONSTRAINT film_user_pkey
        PRIMARY KEY (film_id, user_id),
    CONSTRAINT film_user_fkey
        FOREIGN KEY (film_id)
            REFERENCES films (film_id)
            ON delete CASCADE,
    CONSTRAINT user_film_fkey
        FOREIGN KEY (user_id)
            REFERENCES users (user_id)
            ON delete CASCADE
);